### **1. Indicizzazione booleana**

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: **2, 3, 5, 7, 11, 13, 17, 19**.

2. Utilizza un test logico (ad esempio `>`, `<`, `==`, `!=`) per **selezionare tutte le voci del vettore maggiori di 10**.

3. Utilizza un test logico per selezionare **tutti i numeri primi pari** dalla lista.  


In [1]:
import numpy as np

# 1. Vettore dei numeri primi tra 0 e 20
numeri_primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])

# 2. Seleziono quelle maggiori di 10
maggiori_di_10 = numeri_primi[numeri_primi > 10]
print("Maggiori di 10:", maggiori_di_10)

# 3. Seleziono i primi pari (solo il 2)
primi_pari = numeri_primi[numeri_primi % 2 == 0]
print("Numeri primi pari:", primi_pari)

Maggiori di 10: [11 13 17 19]
Numeri primi pari: [2]


### **2.  Operazioni su array**
Crea un array **a**, 2D (senza digitarlo esplicitamente), e genera due nuovi array **b**, contenente la sua 2ª e 4ª riga, e **c** contenente solo la 3ª.  Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [8]:
import numpy as np

# 1. Creo array a 5x4 con arange e reshape (5 righe, 4 colonne)
a = np.arange(20).reshape(5, 4)

# 2. b = seconda e quarta riga (indici 1 e 3)
b = a[[1, 3], :]

# 3. c = solo la terza riga (indice 2)
c = a[2, :]

# 4. Divido ogni colonna di a per l'elemento corrispondente di c (broadcasting)
divisione = a / c

# 5. Stampo il tutto
print("\nArray a:\n", a)
print("\nArray b (2ª e 4ª riga):\n", b)
print("\nArray c (3ª riga):\n", c)
print("\nArray diviso (ogni colonna di a divisa per c):\n", divisione)


Array a:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Array b (2ª e 4ª riga):
 [[ 4  5  6  7]
 [12 13 14 15]]

Array c (3ª riga):
 [ 8  9 10 11]

Array diviso (ogni colonna di a divisa per c):
 [[0.         0.11111111 0.2        0.27272727]
 [0.5        0.55555556 0.6        0.63636364]
 [1.         1.         1.         1.        ]
 [1.5        1.44444444 1.4        1.36363636]
 [2.         1.88888889 1.8        1.72727273]]


### **3. Seleziona il numero più vicino a 0.5 in un array casuale**
Genera un array 10 x 3 con numeri casuali nell'intervallo [0,1].
Per ogni riga, seleziona il numero più vicino a 0.5. Per farlo usa il fancy indexing.

In [22]:
import numpy as np

# 1. Genero array 10x3 con numeri casuali in [0,1)
array = np.random.rand(10, 3)

# 2. Calcolo la distanza assoluta da 0.5
distanza = np.abs(array - 0.5)

# 3. Trovo l'indice di colonna del minimo per ogni riga
indici_colonna = np.argmin(distanza, axis=1)

# 4. Seleziono i valori corrispondenti (fancy indexing)
valori_scelti = array[np.arange(10), indici_colonna]

# 5. Stampo il tutto
print("Array originale:\n", array, "\n")
print("Indici dei valori più vicini a 0.5:", indici_colonna, "\n")
print("Valori più vicini a 0.5 per ogni riga:\n", valori_scelti)

Array originale:
 [[0.4414813  0.67819765 0.76734195]
 [0.79999551 0.07917034 0.8556639 ]
 [0.73069621 0.90728142 0.60770313]
 [0.45490183 0.26505281 0.89225236]
 [0.14883551 0.03524842 0.98467616]
 [0.27526135 0.55955729 0.3938724 ]
 [0.86221823 0.01549779 0.4844439 ]
 [0.20779877 0.74901988 0.25074793]
 [0.31054896 0.54680352 0.03869373]
 [0.6885702  0.2147671  0.84521109]] 

Indici dei valori più vicini a 0.5: [0 0 2 0 0 1 2 1 1 0] 

Valori più vicini a 0.5 per ogni riga:
 [0.4414813  0.79999551 0.60770313 0.45490183 0.14883551 0.55955729
 0.4844439  0.74901988 0.54680352 0.6885702 ]


### **4. Analisi della Frequenza Cardiaca con NumPy**

1. **Supponiamo che i seguenti valori rappresentino la tua frequenza cardiaca** registrata dal tuo Fitbit durante la giornata:  
   `68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70`  
   Inserisci questi valori in un array NumPy.

2. **Trova la frequenza cardiaca minima** registrata durante la giornata.  
   _(Questo valore rappresenta approssimativamente la tua frequenza cardiaca a riposo, un comune indicatore di salute.)_

3. **Trova la frequenza cardiaca massima** registrata durante la giornata.  
   _(Questo valore è un'indicazione dell'intensità dell'esercizio fisico.)_

4. **Calcoliamo la percentuale di letture effettuate mentre stavi facendo esercizio fisico (frequenza cardiaca sopra a 120)**:  
   - Crea un nuovo array che contiene `True` quando la frequenza cardiaca è **superiore a 120**, e `False` quando è **inferiore o uguale a 120**.
   - Utilizza una funzione di sintesi per calcolare la percentuale di osservazioni in cui la tua frequenza cardiaca era sopra 120.


In [28]:
import numpy as np

# 1. Inserisco i dati in un array
frequenze = np.array([68, 65, 77, 110, 160, 161, 162, 161, 160, 161, 
                      162, 163, 164, 163, 162, 100, 90, 97, 72, 60, 70])

# 2. Calcolo la frequenza minima e massima
min_freq = np.min(frequenze) # Minima
max_freq = np.max(frequenze) # Massima

# 3. Calcolo la percentuale di letture sopra i 120
sopra_120 = frequenze > 120
percentuale = np.mean(sopra_120) * 100

# 4. Stampo tutti i risultati
print("Frequenze cardiache registrata durante la giornata:\n", frequenze, "\n")
print(f"Frequenza minima:",  min_freq, "\n")
print(f"Frequenza massima:", max_freq, "\n")
print(f"Percentuale di letture sopra 120: {percentuale:.1f}%")

Frequenze cardiache registrata durante la giornata:
 [ 68  65  77 110 160 161 162 161 160 161 162 163 164 163 162 100  90  97
  72  60  70] 

Frequenza minima: 60 

Frequenza massima: 164 

Percentuale di letture sopra 120: 52.4%


### **5. Manipolazione di vettori**

1. Creare un vettore contenente i seguenti stipendi: **50.000, 105.250, 55.000, 89.000**.  
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.  
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna **105.250 dollari**, riceva un aumento del **15%**.

3. Il **115%** di **105.250 dollari** è **121.037,50 dollari**.  
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo?

4. Ricrea il vettore e utilizza l'argomento **`dtype`** in modo che, quando il CEO riceve un aumento del **15%**, il suo stipendio finale sia esattamente **121.037,50 dollari**.

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (**50.000 dollari**), che ora pretende un aumento del **20%**.  
Modifica il vettore per riflettere questo cambiamento.

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del **10%**.  
Modifica il vettore di conseguenza.

7. Calcola il **costo totale del personale** dopo tutti gli aumenti.  
Alla fine, quanto è costato all'azienda l'aumento di circa **16.000 dollari** del CEO?


In [57]:
import numpy as np

# 1. Creo il vettore stipendi e calcolo il costo totale del personale
stipendi = np.array ([50000, 105250, 55000, 89000])        # Vettore stipendi
costo_del_personale = np.sum(stipendi)                     # Costo del personale


# 2. Aumento del 15% per il CEO (stipendio 105250) con interi (per vedere l'errore)
stipendi_CEO_aumentato = stipendi.copy()                        # Copia per non modificare l'originale
stipendi_CEO_aumentato[1] = stipendi_CEO_aumentato[1] * 1.15    # 105250 * 1.15 = 121037.5 → viene troncato a 121037


# 3. Il 115% di 105250 è 121037.50? E' presente nell'array? Se no perchè?
valore_atteso = 121037.50
presente = valore_atteso in stipendi_CEO_aumentato

# 4. Ricreare l'array con dtype=float e ripetere l'aumento del CEO ottenendo esattamente 121037.50
stipendi_float = np.array([50000, 105250, 55000, 89000], dtype=float)
stipendi_float[1] = stipendi_float[1] * 1.15                    # Ora diventa 121037.5


# 5. Aumento del 20 % al dipendente con stipendio più basso (50000)
indice_min = np.argmin(stipendi_float)                          # Indice del valore minimo (0)
stipendi_float[indice_min] = stipendi_float[indice_min] * 1.20  # 50000 * 1.20 = 60000


# 6. Aumento del 10 % agli altri due dipendenti
for i in range(len(stipendi_float)):
    if i != 1 and i != indice_min:                              # i != 1 → non CEO, i != indice_min → non il più basso
        stipendi_float[i] = stipendi_float[i] * 1.10


# 7. Nuovo costo totale e differenza
totale_finale = np.sum(stipendi_float)
aumento_totale = totale_finale - costo_del_personale


# Print finali
print ("PUNTO 1:")
print("Vettore degli stipendi iniziali: ", stipendi)
print("Costo totale del personale: ", costo_del_personale, "\n")

print ("PUNTO 2:")
print("Stipendi dopo l'aumento del CEO (con interi):", stipendi_CEO_aumentato)
print("Il valore del CEO è diventato:", stipendi_CEO_aumentato[1], "\n")

print ("PUNTO 3:")
print(f"Valore atteso: {valore_atteso}")
print("È presente nell'array?", presente)
print("Motivo: L'array è di tipo intero, quindi la moltiplicazione per 1.15 ha prodotto 121037.5 ma è stato troncato a 121037. Il valore decimale non può essere rappresentato in un array intero." , "\n")

print("PUNTO 4")
print("Stipendi con float dopo aumento CEO:", stipendi_float)
print("Il valore del CEO è ora esattamente:", stipendi_float[1], "\n")

print("PUNTO 5")
print("Indice del dipendente con stipendio più basso:", indice_min)
print("Vettore degli stipendi dopo l'aumento (20 %) dell'impiegata:", stipendi_float, "\n")


print("PUNTO 6")
print("Vettore dopo l'aumento (10 %) degli altri dipendenti:", stipendi_float, "\n")

print("PUNTO 7")
print("Costo totale del personale dopo tutti gli aumenti:", totale_finale)
print("Aumento totale subito dall'azienda:", aumento_totale)

PUNTO 1:
Vettore degli stipendi iniziali:  [ 50000 105250  55000  89000]
Costo totale del personale:  299250 

PUNTO 2:
Stipendi dopo l'aumento del CEO (con interi): [ 50000 121037  55000  89000]
Il valore del CEO è diventato: 121037 

PUNTO 3:
Valore atteso: 121037.5
È presente nell'array? False
Motivo: L'array è di tipo intero, quindi la moltiplicazione per 1.15 ha prodotto 121037.5 ma è stato troncato a 121037. Il valore decimale non può essere rappresentato in un array intero. 

PUNTO 4
Stipendi con float dopo aumento CEO: [ 60000.  121037.5  60500.   97900. ]
Il valore del CEO è ora esattamente: 121037.49999999999 

PUNTO 5
Indice del dipendente con stipendio più basso: 0
Vettore degli stipendi dopo l'aumento (20 %) dell'impiegata: [ 60000.  121037.5  60500.   97900. ] 

PUNTO 6
Vettore dopo l'aumento (10 %) degli altri dipendenti: [ 60000.  121037.5  60500.   97900. ] 

PUNTO 7
Costo totale del personale dopo tutti gli aumenti: 339437.5
Aumento totale subito dall'azienda: 40187.5

### **6. Valori di Co2**

1. Carica tramite numpy il file generato e salvato a lezione sulle emissioni di CO2

2. Calcola quanti valori ci CO2 sono sopra la soglia di 18  tonnellate per anno ed il loro valore medio

3. Calcola la frazione totale di emissione sopra la soglia (somma totale sopra la soglia/somma totale)

In [62]:
import numpy as np

# 1. Generazione e salvataggio del file (se non esiste gia).
#    Simula la creazione del file "emissioni.txt" con 200 valori casuali tra 4 e 20
file_name = "emissioni.txt"
co2_emissioni = np.round(np.random.uniform(4, 20, 200), 2)

# Nome del file di output
output_file = "emissioni.txt"  # Salva il file nella cartella di lavoro corrente
np.savetxt(output_file, co2_emissioni, fmt="%.2f")


# 2. Carico il file
co2 = np.loadtxt('emissioni.txt')


# 3. Calcoli
soglia = 18                                 # Soglia di 18 tonnellate
co2_sopra_soglia = co2[co2 > soglia]        # Filtro i valori sopra la soglia
num_sopra = len(co2_sopra_soglia)           # Calcolo quanti valori sono sopra la soglia
media_sopra = np.mean(co2_sopra_soglia)     # Calcolo la media delle emissioni sopra la soglia


somma_sopra = np.sum(co2_sopra_soglia)      # Somma delle emissioni sopra la soglia
somma_totale = np.sum(co2)                  # Somma totale di tutte le emissioni
frazione = somma_sopra / somma_totale       # Calcolo la frazione

# Print finali
print(f"Numero di valori sopra {soglia} tonnellate: {num_sopra}")
print(f"Media di questi valori: {media_sopra:.2f}\n")
print(f"Somma sopra soglia: {somma_sopra:.2f}")
print(f"Somma totale: {somma_totale:.2f}")
print(f"Frazione di emissione totale sopra la soglia: {frazione:.4f}")

Numero di valori sopra 18 tonnellate: 27
Media di questi valori: 19.02

Somma sopra soglia: 513.41
Somma totale: 2442.91
Frazione di emissione totale sopra la soglia: 0.2102


### **7. Analisi di una matrice**
Data la matrice survey con età, reddito e anni di istruzione

survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


1. Seleziona dalla matrice solo gli intervistati con **almeno 12 anni di istruzione** utilizzando un test logico.

2. In un'unica riga di codice, seleziona i **redditi** degli intervistati con **almeno 12 anni di istruzione**.

3. In un'unica riga di codice, calcola il **reddito medio** degli intervistati con **almeno 12 anni di istruzione**.


In [68]:
import numpy as np

# 1. Definizione della matrice survey (età, reddito, anni, istruzione)
survey_matrix = np.array([
    [25, 40000, 10],
    [32, 52000, 12],
    [40, 63000, 14],
    [29, 47000, 11],
    [35, 58000, 13]
])


# 2. Calcoli
selezione = survey_matrix[survey_matrix[:, 2] >= 12]       # Intervistati con almeno 12 anni di istruzione
redditi_selezionati = selezione[:, 1]                      # Redditi degli intervistati
reddito_medio = round(np.mean(redditi_selezionati), 2)     # Reddito medio (arrotondo a 2 decimali)


# Print finali
print("Intervistati con almeno 12 anni di istruzione:\n", selezione, "\n")
print("Redditi degli intervistati:", redditi_selezionati, "\n")
print(f"Reddito medio degli intervistati: {reddito_medio}")

Intervistati con almeno 12 anni di istruzione:
 [[   32 52000    12]
 [   40 63000    14]
 [   35 58000    13]] 

Redditi degli intervistati: [52000 63000 58000] 

Reddito medio degli intervistati: 57666.67


### **8. Rimpiazzare gli outliers**

Vediamo se possiamo ripulire alcuni dati mancanti. Immagina di essere il responsabile dei registri di un comune locale con **500 cittadini** di **55 anni e oltre**.  

La città è famosa per la sua longevità e un team di ricercatori ti ha chiesto di identificare **il cittadino più anziano**.  

Il problema è che, occasionalmente, nei registri si verificano errori e in quei casi viene inserita l'età **999** invece dell'età corretta.  

Rimuovi i dati errati dall'array e determina l'età del cittadino più anziano.


In [ ]:
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90,  55,  55,  96, 109,  82,  55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

In [69]:
import numpy as np

# Dati dell'età
ages = np.array([92, 108, 75, 63, 62, 66, 90, 98, 97, 92, 60, 107, 90, 71, 97, 86, 55, 55,
                 98, 57, 96, 104, 96, 94, 72, 98, 111, 98, 89, 69, 77, 92, 85, 101, 93, 100,
                 90, 101, 96, 98, 999, 87, 106, 86, 108, 55, 67, 65, 68, 59, 67, 72, 57, 79,
                 95, 67, 86, 70, 91, 111, 67, 75, 59, 88, 90, 99, 94, 65, 111, 103, 100, 70,
                 63, 65, 100, 110, 999, 70, 57, 75, 56, 104, 111, 90, 74, 100, 90, 86, 88, 99,
                 58, 103, 88, 103, 64, 96, 105, 89, 83, 65, 100, 62, 73, 105, 83, 105, 58, 96,
                 77, 74, 95, 109, 91, 101, 91, 999, 63, 111, 97, 108, 75, 77, 73, 58, 94, 83,
                 90, 61, 110, 107, 105, 85, 64, 66, 71, 107, 105, 72, 78, 66, 100, 102, 72, 999,
                 74, 68, 73, 72, 90, 93, 99, 55, 92, 83, 58, 71, 89, 75, 98, 87, 999, 78,
                 97, 71, 106, 83, 58, 81, 100, 72, 93, 70, 65, 60, 95, 107, 94, 77, 87, 90,
                 82, 56, 99, 107, 86, 56, 73, 96, 64, 69, 64, 92, 57, 104, 110, 69, 66, 68,
                 84, 89, 72, 80, 55, 75, 87, 57, 106, 69, 66, 62, 102, 76, 111, 999, 96, 83,
                 84, 61, 102, 63, 107, 63, 76, 58, 83, 58, 61, 71, 77, 90, 74, 100, 103, 74,
                 92, 102, 63, 87, 93, 61, 63, 86, 74, 98, 64, 999, 78, 95, 84, 81, 107, 85,
                 79, 82, 89, 65, 107, 57, 74, 77, 97, 92, 58, 96, 105, 60, 55, 74, 57, 80,
                 62, 85, 87, 62, 999, 71, 74, 70, 97, 59, 82, 96, 105, 70, 89, 105, 60, 70,
                 87, 999, 64, 108, 107, 104, 85, 95, 108, 74, 64, 97, 89, 88, 79, 67, 81, 92,
                 63, 80, 76, 94, 104, 67, 73, 61, 99, 96, 68, 90, 86, 79, 85, 111, 75, 98,
                 81, 111, 108, 103, 85, 72, 108, 102, 999, 64, 107, 112, 66, 93, 89, 78, 66, 92,
                 63, 101, 92, 64, 72, 56, 71, 64, 87, 78, 107, 85, 109, 95, 69, 111, 64, 72,
                 55, 66, 99, 57, 78, 55, 58, 90, 88, 71, 90, 103, 92, 98, 67, 97, 77, 68,
                 77, 59, 78, 69, 77, 81, 61, 99, 999, 85, 78, 104, 97, 95, 74, 70, 69, 83,
                 68, 68, 77, 60, 85, 82, 93, 66, 71, 62, 64, 107, 999, 65, 78, 59, 83, 67,
                 108,  58,  95, 106,  83,  79,  67,  59,  96,  90, 55, 55, 96, 109,  82, 55, 101,  58,
                 97, 77, 60, 81, 999, 81, 75, 100, 66, 65, 105, 94, 101, 56, 999, 59, 105, 59,
                 93, 56, 104, 74, 81, 62, 76, 65, 107, 60, 107, 98, 77, 86, 83, 104, 74, 69,
                 97, 80, 91, 56, 108, 87, 65, 91, 93, 60, 91, 110, 107, 88, 96, 70, 60, 99,
                 66, 91, 107, 65, 81, 109, 84, 106, 80, 92, 78, 84, 91, 59])

# 1. Rimuovo i valori errati (999)
valid_ages = ages[ages != 999]

# 2. Determino l'età del cittadino più anziano
oldest = np.max(valid_ages)

# Stampo i risultati
print(f"Numero di valori totali: {len(ages)}")
print(f"Numero di outlier (999) rimossi: {len(ages) - len(valid_ages)}")
print(f"Età del cittadino più anziano (dopo pulizia): {oldest}")

Numero di valori totali: 500
Numero di outlier (999) rimossi: 14
Età del cittadino più anziano (dopo pulizia): 112


### 9.**Generazione random di storie**

Usando la lista qui sotto, estrai casualmente **5 parole con reinserimento** (cioè, i duplicati sono ammessi).  

Successivamente, inserisci casualmente queste parole negli spazi vuoti (indicati con "_") nella seguente frase:

*"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico __ che proteggeva. Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante e le offrì il __ come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "__".  
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un __.  
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.  
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: "Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza _!" Ci fu grande gioia e celebrazione."*


In [ ]:
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]



Esempio di output


"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico APPLICAZIONE che proteggeva. 
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante 
e le offrì il DEPOSITO come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "PRESTAZIONE".  

Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un BIRILLO DA BOWLING. 
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo. 
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse: 
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza GIUSTIFICAZIONE!"  

Ci fu grande gioia e celebrazione."

In [82]:
import random

# Lista delle parole fornita
lista_parole = [
    'INSEDIAMENTO', 'SEPARAZIONE', 'DIFFERENZA', 'APPLICAZIONE', 'ATTEGGIAMENTO', 'VERDURA', 'IMPERO', 'RICEVIMENTO',
    'IGNORANZA', 'BIOGRAFIA', 'VISIONE', 'AGENTE DI POLIZIA', 'PROVA', 'PRESTAZIONE', 'PRESENTAZIONE', 'PARENTE',
    'GIUSTIFICAZIONE', 'FILOSOFIA', 'DIREZIONE', 'BENEFICIARIO', 'BATTERIA', 'CERIMONIA', 'AGONIA', 'RECUPERO',
    'ALFABETIZZAZIONE', 'CONSEGNA', 'SERBATOIO', 'VOLONTARIO', 'DEPOSITO', 'BIRILLO DA BOWLING', 'NEMICO', 'ANNUNCIO',
    'CARAMELLA ZUCCHERATA', 'FULMINE', 'PALLONCINO', 'COPERTA', 'SCOPERTA', 'PENALITÀ', 'GENERALE', 'ALPACA',
    'VANTAGGIO', 'HOT DOG', 'ABITO', 'MATEMATICA', 'VARIANTE'
]

# 1. Estraggo 5 parole casuali con reinserimento
parole_estratte = random.choices(lista_parole, k=5)

# 2. Costruisco la frase sostituendo gli spazi vuoti
frase = (f"In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico {parole_estratte[0]} che proteggeva.\n"
         f"Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante\n"
         f"e le offrì il {parole_estratte[1]} come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, \"{parole_estratte[2]}\".\n"
         f"Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un {parole_estratte[3]}.\n"
         f"Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.\n"
         f"Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:\n"
         f"\"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza {parole_estratte[4]}!\"\n"
         "Ci fu grande gioia e celebrazione.")

# 3. Stampo la frase completa
print(frase)

In epoche passate, viveva una donna saggia che era molto orgogliosa dell'antico CERIMONIA che proteggeva.
Quando un anziano del villaggio venne a chiederle consiglio su come garantire al meglio un raccolto abbondante
e le offrì il BATTERIA come dono, i suoi occhi si spalancarono e lei esclamò una sola parola, "CONSEGNA".
Radunò il villaggio e, per i successivi 100 giorni, su sua richiesta, gli abitanti cercarono nella foresta un RICEVIMENTO.
Nel 101° giorno, il bambino più giovane del villaggio trovò ciò che stavano cercando e tutti corsero dalla donna saggia per donarglielo.
Con un sorriso da un orecchio all’altro, e cantando canti di festa, la donna saggia guardò i suoi compaesani e disse:
"Ora è giunto il tempo del banchetto - nessuno rimarrà mai più senza DIREZIONE!"
Ci fu grande gioia e celebrazione.
